server:
  port: 8080

spring:
  application:
    name: magalu-connect
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/db-magalu-connect
    username: magalu-connect
    password: magalu-connect
  jpa:
    hibernate:
      ddl-auto: none
    generate-ddl: false
    show-sql: true
    properties:
      hibernate:
        show_sql: true
        format_sql: true
  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.xml

logging:
  level:
    com.rosivaldolucas.magalu_connect: TRACE
    root: INFO
    org.springframework.web: DEBUG
    org.hibernate: INFO
