server:
  port: 8080
  error:
    whitelabel:
      enabled: false

spring:
  application:
    name: magalu-connect
  web:
    resources:
      add-mappings: false

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/db-magalu-connect
    username: magalu-connect
    password: magalu-connect
  jpa:
    hibernate:
      ddl-auto: update
    generate-ddl: true
    show-sql: true
    properties:
      hibernate:
        show_sql: true
        format_sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
