server:
  port: 8080
  error:
    whitelabel:
      enabled: false

proxy:
  host:
  port:
  enabled:

spring:
  mvc:
    throw-exception-if-no-handler-found: true
  web:
    resources:
      add-mappings: false

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/db-magalu-connect
    username: magalu-connect
    password: magalu-connect
  jpa:
    hibernate:
      ddl-auto: none
    generate-ddl: false
    show-sql: true
    properties:
      hibernate:
        show_sql: true
        format_sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.xml

  mail:
    host: smtp.gmail.com
    port: 587
    username: rosilucas999@gmail.com
    password: cbmj kioq lqpu vkoo
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true

s3:
  bucket: awslocalstack

#logging:
#  file:
#    path: @logs.path@
#
#info:
#  app:
#    name: @artifactId@
#    version: @version@
#    description: @name@
#    contact: rosilucas999@gmail.com
#    ip: ${spring.cloud.client.ip-address}
#    profile: ${spring.profiles.active}
